// 种子话题库：按「真实学科」组织的概念集，主题=学科，话题=该学科里真实存在的概念。
//
// 设计原则（回应上一版「自己编主题 + 随意配对」的问题）：
//  · 主题本身就是标准学科（哲学 / 心理学 / 经济学 / 社会学 / 逻辑与数学），
//    不是临时拼出来的分类；
//  · 每个话题都是该学科里真实、可查证的概念（教材 / 文献里实际存在的词），不是编造的词组；
//  · 心理学取自 Buster Benson《Cognitive Bias Cheat Sheet》认知偏误体系；
//    其余学科取自各学科标准概念表（哲学概念、经济学名词、社会学理论、逻辑与数学悖论）。
// 每条取概念名作为 term，category 用学科英文 id，与 lib/prompts.ts 的 categories 对应。
// 仅作静态种子数据，运行时可通过「设置 → 导入」追加个人词库。
import type { Prompt } from "./prompts";

export const seedTopics: Prompt[] = [
  // ===== 哲学 philosophy：真实哲学概念与理论 =====
  { id: "seed::philosophy::1", term: "存在主义", category: "philosophy" },
  { id: "seed::philosophy::2", term: "功利主义", category: "philosophy" },
  { id: "seed::philosophy::3", term: "虚无主义", category: "philosophy" },
  { id: "seed::philosophy::4", term: "决定论", category: "philosophy" },
  { id: "seed::philosophy::5", term: "自由意志", category: "philosophy" },
  { id: "seed::philosophy::6", term: "缸中之脑", category: "philosophy" },
  { id: "seed::philosophy::7", term: "洞穴寓言", category: "philosophy" },
  { id: "seed::philosophy::8", term: "社会契约论", category: "philosophy" },
  { id: "seed::philosophy::9", term: "先验与经验", category: "philosophy" },
  { id: "seed::philosophy::10", term: "二律背反", category: "philosophy" },
  { id: "seed::philosophy::11", term: "异化", category: "philosophy" },
  { id: "seed::philosophy::12", term: "荒诞", category: "philosophy" },
  { id: "seed::philosophy::13", term: "他者", category: "philosophy" },
  { id: "seed::philosophy::14", term: "本质先于存在", category: "philosophy" },
  { id: "seed::philosophy::15", term: "辩证法", category: "philosophy" },
  { id: "seed::philosophy::16", term: "实用主义", category: "philosophy" },
  { id: "seed::philosophy::17", term: "相对主义", category: "philosophy" },
  { id: "seed::philosophy::18", term: "还原论", category: "philosophy" },
  { id: "seed::philosophy::19", term: "整体论", category: "philosophy" },
  { id: "seed::philosophy::20", term: "二元论", category: "philosophy" },
  { id: "seed::philosophy::21", term: "物理主义", category: "philosophy" },
  { id: "seed::philosophy::22", term: "泛心论", category: "philosophy" },
  { id: "seed::philosophy::23", term: "休谟铡刀", category: "philosophy" },
  { id: "seed::philosophy::24", term: "无知之幕", category: "philosophy" },
  { id: "seed::philosophy::25", term: "语言游戏", category: "philosophy" },
  { id: "seed::philosophy::26", term: "目的论", category: "philosophy" },
  { id: "seed::philosophy::27", term: "唯名论与实在论", category: "philosophy" },
  { id: "seed::philosophy::28", term: "斯多葛主义", category: "philosophy" },
  { id: "seed::philosophy::29", term: "经验主义", category: "philosophy" },
  { id: "seed::philosophy::30", term: "理性主义", category: "philosophy" },
  { id: "seed::philosophy::31", term: "同一性", category: "philosophy" },
  { id: "seed::philosophy::32", term: "快乐主义", category: "philosophy" },

  // ===== 心理学 psychology：认知偏误体系（Buster Benson 分类） =====
  { id: "seed::psychology::1", term: "锚定效应", category: "psychology" },
  { id: "seed::psychology::2", term: "确认偏误", category: "psychology" },
  { id: "seed::psychology::3", term: "幸存者偏差", category: "psychology" },
  { id: "seed::psychology::4", term: "可得性启发", category: "psychology" },
  { id: "seed::psychology::5", term: "框架效应", category: "psychology" },
  { id: "seed::psychology::6", term: "损失厌恶", category: "psychology" },
  { id: "seed::psychology::7", term: "沉没成本谬误", category: "psychology" },
  { id: "seed::psychology::8", term: "邓宁-克鲁格效应", category: "psychology" },
  { id: "seed::psychology::9", term: "从众效应", category: "psychology" },
  { id: "seed::psychology::10", term: "光环效应", category: "psychology" },
  { id: "seed::psychology::11", term: "自利偏差", category: "psychology" },
  { id: "seed::psychology::12", term: "后见之明偏差", category: "psychology" },
  { id: "seed::psychology::13", term: "控制错觉", category: "psychology" },
  { id: "seed::psychology::14", term: "虚假共识效应", category: "psychology" },
  { id: "seed::psychology::15", term: "现状偏误", category: "psychology" },
  { id: "seed::psychology::16", term: "禀赋效应", category: "psychology" },
  { id: "seed::psychology::17", term: "计划谬误", category: "psychology" },
  { id: "seed::psychology::18", term: "宜家效应", category: "psychology" },
  { id: "seed::psychology::19", term: "峰终定律", category: "psychology" },
  { id: "seed::psychology::20", term: "赌徒谬误", category: "psychology" },
  { id: "seed::psychology::21", term: "基本归因错误", category: "psychology" },
  { id: "seed::psychology::22", term: "旁观者效应", category: "psychology" },
  { id: "seed::psychology::23", term: "刻板印象", category: "psychology" },
  { id: "seed::psychology::24", term: "安慰剂效应", category: "psychology" },
  { id: "seed::psychology::25", term: "巴纳姆效应", category: "psychology" },
  { id: "seed::psychology::26", term: "认知失调", category: "psychology" },
  { id: "seed::psychology::27", term: "习得性无助", category: "psychology" },
  { id: "seed::psychology::28", term: "自我实现预言", category: "psychology" },
  { id: "seed::psychology::29", term: "破窗效应", category: "psychology" },
  { id: "seed::psychology::30", term: "聚光灯效应", category: "psychology" },
  { id: "seed::psychology::31", term: "知识诅咒", category: "psychology" },
  { id: "seed::psychology::32", term: "乐观偏差", category: "psychology" },
  { id: "seed::psychology::33", term: "选择性知觉", category: "psychology" },
  { id: "seed::psychology::34", term: "群体思维", category: "psychology" },
  { id: "seed::psychology::35", term: "证实偏差", category: "psychology" },

  // ===== 经济学 economics：标准经济学概念 =====
  { id: "seed::economics::1", term: "机会成本", category: "economics" },
  { id: "seed::economics::2", term: "边际效用", category: "economics" },
  { id: "seed::economics::3", term: "比较优势", category: "economics" },
  { id: "seed::economics::4", term: "复利", category: "economics" },
  { id: "seed::economics::5", term: "通货膨胀", category: "economics" },
  { id: "seed::economics::6", term: "供给与需求", category: "economics" },
  { id: "seed::economics::7", term: "需求弹性", category: "economics" },
  { id: "seed::economics::8", term: "外部性", category: "economics" },
  { id: "seed::economics::9", term: "公共物品", category: "economics" },
  { id: "seed::economics::10", term: "博弈论", category: "economics" },
  { id: "seed::economics::11", term: "纳什均衡", category: "economics" },
  { id: "seed::economics::12", term: "囚徒困境", category: "economics" },
  { id: "seed::economics::13", term: "信息不对称", category: "economics" },
  { id: "seed::economics::14", term: "逆向选择", category: "economics" },
  { id: "seed::economics::15", term: "道德风险", category: "economics" },
  { id: "seed::economics::16", term: "规模经济", category: "economics" },
  { id: "seed::economics::17", term: "垄断", category: "economics" },
  { id: "seed::economics::18", term: "吉芬商品", category: "economics" },
  { id: "seed::economics::19", term: "搭便车问题", category: "economics" },
  { id: "seed::economics::20", term: "稀缺性", category: "economics" },
  { id: "seed::economics::21", term: "乘数效应", category: "economics" },
  { id: "seed::economics::22", term: "流动性陷阱", category: "economics" },
  { id: "seed::economics::23", term: "帕累托最优", category: "economics" },
  { id: "seed::economics::24", term: "看不见的手", category: "economics" },
  { id: "seed::economics::25", term: "理性预期", category: "economics" },
  { id: "seed::economics::26", term: "行为经济学", category: "economics" },
  { id: "seed::economics::27", term: "心理账户", category: "economics" },
  { id: "seed::economics::28", term: "菜单成本", category: "economics" },
  { id: "seed::economics::29", term: "创造性破坏", category: "economics" },
  { id: "seed::economics::30", term: "交易成本", category: "economics" },
  { id: "seed::economics::31", term: "沉没成本", category: "economics" },
  { id: "seed::economics::32", term: "理性人假设", category: "economics" },

  // ===== 社会学 sociology：社会理论与经典议题 =====
  { id: "seed::sociology::1", term: "社会资本", category: "sociology" },
  { id: "seed::sociology::2", term: "科层制", category: "sociology" },
  { id: "seed::sociology::3", term: "镜中我", category: "sociology" },
  { id: "seed::sociology::4", term: "拟剧理论", category: "sociology" },
  { id: "seed::sociology::5", term: "标签理论", category: "sociology" },
  { id: "seed::sociology::6", term: "差序格局", category: "sociology" },
  { id: "seed::sociology::7", term: "社会分层", category: "sociology" },
  { id: "seed::sociology::8", term: "社会流动", category: "sociology" },
  { id: "seed::sociology::9", term: "参照群体", category: "sociology" },
  { id: "seed::sociology::10", term: "沉默的螺旋", category: "sociology" },
  { id: "seed::sociology::11", term: "文化资本", category: "sociology" },
  { id: "seed::sociology::12", term: "惯习", category: "sociology" },
  { id: "seed::sociology::13", term: "场域", category: "sociology" },
  { id: "seed::sociology::14", term: "符号互动论", category: "sociology" },
  { id: "seed::sociology::15", term: "结构功能主义", category: "sociology" },
  { id: "seed::sociology::16", term: "冲突理论", category: "sociology" },
  { id: "seed::sociology::17", term: "社会事实", category: "sociology" },
  { id: "seed::sociology::18", term: "集体记忆", category: "sociology" },
  { id: "seed::sociology::19", term: "弱关系", category: "sociology" },
  { id: "seed::sociology::20", term: "六度分隔", category: "sociology" },
  { id: "seed::sociology::21", term: "内群体与外群体", category: "sociology" },
  { id: "seed::sociology::22", term: "社会认同理论", category: "sociology" },
  { id: "seed::sociology::23", term: "角色冲突", category: "sociology" },
  { id: "seed::sociology::24", term: "去个体化", category: "sociology" },
  { id: "seed::sociology::25", term: "破窗理论", category: "sociology" },
  { id: "seed::sociology::26", term: "路径依赖", category: "sociology" },
  { id: "seed::sociology::27", term: "代际流动", category: "sociology" },
  { id: "seed::sociology::28", term: "世俗化", category: "sociology" },
  { id: "seed::sociology::29", term: "相对剥夺感", category: "sociology" },

  // ===== 逻辑与数学 logic-math：悖论、定理与思维工具 =====
  { id: "seed::logic-math::1", term: "芝诺悖论", category: "logic-math" },
  { id: "seed::logic-math::2", term: "说谎者悖论", category: "logic-math" },
  { id: "seed::logic-math::3", term: "罗素悖论", category: "logic-math" },
  { id: "seed::logic-math::4", term: "哥德尔不完备定理", category: "logic-math" },
  { id: "seed::logic-math::5", term: "理发师悖论", category: "logic-math" },
  { id: "seed::logic-math::6", term: "忒修斯之船", category: "logic-math" },
  { id: "seed::logic-math::7", term: "蒙提霍尔问题", category: "logic-math" },
  { id: "seed::logic-math::8", term: "巴拿赫-塔斯基悖论", category: "logic-math" },
  { id: "seed::logic-math::9", term: "加布里埃尔号角", category: "logic-math" },
  { id: "seed::logic-math::10", term: "费马大定理", category: "logic-math" },
  { id: "seed::logic-math::11", term: "哥德巴赫猜想", category: "logic-math" },
  { id: "seed::logic-math::12", term: "四色定理", category: "logic-math" },
  { id: "seed::logic-math::13", term: "庞加莱猜想", category: "logic-math" },
  { id: "seed::logic-math::14", term: "归谬法", category: "logic-math" },
  { id: "seed::logic-math::15", term: "奥卡姆剃刀", category: "logic-math" },
  { id: "seed::logic-math::16", term: "排中律", category: "logic-math" },
  { id: "seed::logic-math::17", term: "矛盾律", category: "logic-math" },
  { id: "seed::logic-math::18", term: "递归", category: "logic-math" },
  { id: "seed::logic-math::19", term: "图灵机", category: "logic-math" },
  { id: "seed::logic-math::20", term: "停机问题", category: "logic-math" },
  { id: "seed::logic-math::21", term: "康托尔对角线", category: "logic-math" },
  { id: "seed::logic-math::22", term: "贝叶斯定理", category: "logic-math" },
  { id: "seed::logic-math::23", term: "辛普森悖论", category: "logic-math" },
  { id: "seed::logic-math::24", term: "双生子悖论", category: "logic-math" },
  { id: "seed::logic-math::25", term: "祖父悖论", category: "logic-math" },
  { id: "seed::logic-math::26", term: "希尔伯特旅馆悖论", category: "logic-math" },
  { id: "seed::logic-math::27", term: "欧拉公式", category: "logic-math" },
  { id: "seed::logic-math::28", term: "素数无穷", category: "logic-math" },
  { id: "seed::logic-math::29", term: "皮亚诺公理", category: "logic-math" },
  { id: "seed::logic-math::30", term: "康托尔定理", category: "logic-math" },

];
